#!/usr/bin/env python3
"""The detail layer under the milestones on cosmic-timeline.html.

The set comes from a Big History notebook built in Mathematica, which
lays the same span out over eight nested logarithmic scales, from ten
billion years down to one thousand. Every mark here was checked against
the current literature before it was carried across, and the ones that
did not survive the check were corrected or dropped. The corrections are
listed in FIXED at the foot of this file so the change is on the record.

t is years before the present. Strands group the marks into rows.
"""

Y0 = 2026          # the present the calendar dates are measured from


def ya(n):
    """n years ago."""
    return float(n)


def ce(y):
    """A year of the common era."""
    return float(Y0 - y)


def bce(y):
    """A year before the common era, given positive.

    There is no year zero, so 1754 BCE is astronomical year -1753.
    """
    return float(Y0 + y - 1)


STRANDS = [
    ("cos", "Cosmos", "#b48cf2"),
    ("sol", "Solar system", "#ffd24d"),
    ("ear", "Earth", "#e08b5a"),
    ("lif", "Life", "#31d67a"),
    ("ani", "Animals", "#4fbf8b"),
    ("mam", "Mammals", "#7fd4ff"),
    ("pri", "Primates", "#2fc6a6"),
    ("sap", "Us", "#ef5350"),
    ("far", "Farming and cities", "#d4a373"),
    ("sta", "States and empires", "#f2837f"),
    ("sci", "Science and maths", "#58a6ff"),
    ("art", "Arts and belief", "#c78ee0"),
    ("pop", "World population", "#9aa4b2"),
]

# (t in years before now, name, strand)
DETAIL = [
    # ---------------------------------------------------------------- cosmos
    (ya(13.787e9), "The Big Bang", "cos"),
    (ya(13.787e9 - 378e3), "Recombination, and the first light", "cos"),
    (ya(13.6e9), "The first stars, still unobserved", "cos"),
    (ya(13.52e9), "MoM z14, the earliest galaxy seen so far", "cos"),
    (ya(13.5e9), "The first stars die as supernovae", "cos"),
    (ya(13.45e9), "Reionization begins", "cos"),
    (ya(13.4e9), "The cosmic dark ages end", "cos"),
    (ya(13.407e9), "Star clusters draw together into dwarf galaxies", "cos"),
    (ya(13.5e9), "The Milky Way begins to assemble", "cos"),
    (ya(9e9), "The universe is a web of galaxy clusters", "cos"),
    (ya(6e9), "The expansion of the universe starts to accelerate", "cos"),
    (ya(1965), "The microwave background is measured", "cos"),
    # ---------------------------------------------------------- solar system
    (ya(4.567e9), "A nearby supernova seeds the cloud with heavy elements",
     "sol"),
    (ya(4.5682e9), "The cloud collapses and the Sun begins", "sol"),
    (ya(4.564e9), "Jupiter, Saturn, Uranus and Neptune take shape", "sol"),
    (ya(4.55e9), "The Sun ignites, fusing hydrogen into helium", "sol"),
    (ya(4.53e9), "The Sun drifts free of its sibling stars", "sol"),
    (ya(4.54e9), "Earth begins to accrete", "sol"),
    (ya(4.5e9), "Mercury, Venus, Earth and Mars are formed", "sol"),
    (ya(4.51e9), "A Mars-sized body strikes Earth and the Moon forms", "sol"),
    (ya(4.1e9), "The giant planets' orbits shift", "sol"),
    (ya(3.9e9), "The late heavy bombardment, now disputed", "sol"),
    (ya(3.7e9), "Mars loses most of its atmosphere and its water", "sol"),
    (ce(1989), "Voyager 1 passes the last of the planets", "sol"),
    # ----------------------------------------------------------------- earth
    (ya(4.567e9), "The Hadean eon opens", "ear"),
    (ya(4.53e9), "The core separates from the mantle", "ear"),
    (ya(4.4e9), "The first oceans", "ear"),
    (ya(4.0e9), "The Archean eon opens", "ear"),
    (ya(3.2e9), "The first continents stand above the sea", "ear"),
    (ya(2.5e9), "The Proterozoic eon opens", "ear"),
    (ya(2.43e9), "The great oxidation event", "ear"),
    (ya(750e6), "Rodinia breaks up", "ear"),
    (ya(717e6), "Snowball Earth", "ear"),
    (ya(538.8e6), "The Phanerozoic eon opens", "ear"),
    (ya(251.9e6), "The Permian extinction, the largest of them all", "ear"),
    (ya(66.0e6), "The Chicxulub impact", "ear"),
    (ya(115e3), "The last glacial period begins", "ear"),
    (ya(11.7e3), "The last glacial period ends", "ear"),
    # ------------------------------------------------------------------ life
    (ya(4.2e9), "The last universal common ancestor", "lif"),
    (ya(3.48e9), "Stromatolites, the firmest early evidence of life", "lif"),
    (ya(3.2e9), "Bacteria on land", "lif"),
    (ya(2.7e9), "Photosynthesis starts making oxygen", "lif"),
    (ya(2.1e9), "Large colonial fossils in the Francevillian rocks", "lif"),
    (ya(1.85e9), "Cells acquire mitochondria", "lif"),
    (ya(1.65e9), "The firmest early eukaryote fossils", "lif"),
    (ya(1.047e9), "Bangiomorpha, and the oldest evidence of sex", "lif"),
    (ya(750e6), "Sponges, by the molecular clock", "lif"),
    (ya(635e6), "The earliest known animal embryos", "lif"),
    (ya(575e6), "The Ediacaran biota", "lif"),
    (ya(538.8e6), "The Cambrian explosion", "lif"),
    # --------------------------------------------------------------- animals
    (ya(575e6), "Nerve nets, and animals that act on what they sense", "ani"),
    (ya(520e6), "Conodonts leave the first toothlike fossils", "ani"),
    (ya(518e6), "Haikouichthys, among the first fish", "ani"),
    (ya(510e6), "Bonelike tissue", "ani"),
    (ya(480e6), "The great Ordovician biodiversification", "ani"),
    (ya(479e6), "Insects, by the molecular clock", "ani"),
    (ya(470e6), "Spores of the first land plants", "ani"),
    (ya(465e6), "Jawless armoured fish", "ani"),
    (ya(450e6), "Sharks and rays", "ani"),
    (ya(436e6), "Jaws", "ani"),
    (ya(425e6), "Pneumodesmus, breathing air on land", "ani"),
    (ya(420e6), "A fully bony internal skeleton", "ani"),
    (ya(416e6), "Teeth, in a placoderm", "ani"),
    (ya(415e6), "The first lungfish", "ani"),
    (ya(395e6), "Vertebrate tracks on a Polish shore", "ani"),
    (ya(385e6), "The first forests", "ani"),
    (ya(380e6), "Materpiscis, the earliest known live birth", "ani"),
    (ya(375e6), "Elginerpeton, an early tetrapod", "ani"),
    (ya(365e6), "The first seeds", "ani"),
    (ya(330e6), "Giant amphibians", "ani"),
    (ya(324e6), "The first flying insects", "ani"),
    (ya(318e6), "Amniotes, and the shelled egg", "ani"),
    (ya(312e6), "Archaeothyris, an early synapsid", "ani"),
    (ya(310e6), "The first conifers", "ani"),
    (ya(250e6), "Frogs and salamanders", "ani"),
    (ya(231e6), "The earliest dinosaur fossils", "ani"),
    (ya(220e6), "Odontochelys, an early turtle", "ani"),
    (ya(150e6), "Archaeopteryx, and flight in birds", "ani"),
    (ya(130e6), "Flowering plants", "ani"),
    (ya(125e6), "Confuciusornis, the first toothless beak", "ani"),
    # --------------------------------------------------------------- mammals
    (ya(260e6), "Cynodonts, the mammal line", "mam"),
    (ya(225e6), "Mammaliaforms split from their cynodont ancestors", "mam"),
    (ya(210e6), "Milk and deciduous teeth", "mam"),
    (ya(205e6), "Morganucodon", "mam"),
    (ya(165e6), "Castorocauda, and a fossil trace of fur", "mam"),
    (ya(160e6), "Juramaia, the earliest placental", "mam"),
    (ya(125e6), "Sinodelphys, on the marsupial side", "mam"),
    (ya(123e6), "Teinolophos, an early monotreme", "mam"),
    (ya(80e6), "Alphadon, a late Cretaceous marsupial", "mam"),
    (ya(62e6), "Ravenictis, an early carnivoran", "mam"),
    (ya(60e6), "Eritherium, the earliest known elephant", "mam"),
    (ya(60e6), "The first rodents", "mam"),
    (ya(55e6), "Diacodexis, an even-toed hoofed mammal", "mam"),
    (ya(52e6), "The oldest known bats", "mam"),
    (ya(37e6), "Hesperocyon, and the dog family", "mam"),
    # --------------------------------------------------------------- primates
    (ya(66e6), "Purgatorius, the earliest possible primate", "pri"),
    (ya(56e6), "Teilhardina, and firm primates in the record", "pri"),
    (ya(47e6), "Darwinius, preserved in the Messel pit", "pri"),
    (ya(25e6), "Apes", "pri"),
    (ya(15.8e6), "The last common ancestor with orangutans", "pri"),
    (ya(8.9e6), "The last common ancestor with gorillas", "pri"),
    (ya(7e6), "Sahelanthropus, the earliest claimed hominin", "pri"),
    (ya(6.6e6), "The last common ancestor with chimpanzees", "pri"),
    (ya(3.4e6), "Cut marks on bone in Ethiopia, disputed", "pri"),
    (ya(3.3e6), "Lomekwi, the earliest flaked stone", "pri"),
    (ya(3.0e6), "Australopithecus africanus", "pri"),
    (ya(2.8e6), "The genus Homo", "pri"),
    (ya(2.6e6), "Oldowan tools", "pri"),
    (ya(1.76e6), "Acheulean handaxes at Kokiselei", "pri"),
    # -------------------------------------------------------------------- us
    (ya(900e3), "A population bottleneck of about 1,280, disputed", "sap"),
    (ya(790e3), "Controlled fire at Gesher Benot Ya'aqov", "sap"),
    (ya(700e3), "The first extended sea crossing", "sap"),
    (ya(540e3), "A shell engraved by Homo erectus at Trinil", "sap"),
    (ya(500e3), "The first blades, in Kenya and Israel", "sap"),
    (ya(500e3), "Prepared-core technique", "sap"),
    (ya(460e3), "Flaked bone tools in Italy", "sap"),
    (ya(400e3), "Homo neanderthalensis", "sap"),
    (ya(315e3), "Homo sapiens at Jebel Irhoud", "sap"),
    (ya(300e3), "Hafted wooden spears at Schoningen", "sap"),
    (ya(250e3), "Levallois points", "sap"),
    (ya(200e3), "Birch tar, the first synthetic material", "sap"),
    (ya(170e3), "Clothing, dated by the genetics of lice", "sap"),
    (ya(164e3), "Ochre worked at Pinnacle Point", "sap"),
    (ya(142e3), "Shell beads at Bizmoune Cave", "sap"),
    (ya(92e3), "The earliest known burial, at Qafzeh", "sap"),
    (ya(90e3), "Bone harpoons at Katanda", "sap"),
    (ya(84e3), "Bone tools at Blombos", "sap"),
    (ya(82e3), "Bead necklaces at Grotte des Pigeons", "sap"),
    (ya(65e3), "Australia is settled", "sap"),
    (ya(60e3), "Ostrich eggshell engraved at Diepkloof", "sap"),
    (ya(50e3), "Twisted plant fibre made by Neanderthals", "sap"),
    (ya(43e3), "Flutes of bird bone and mammoth ivory", "sap"),
    (ya(42e3), "Offshore fishing from canoes at Jerimalai", "sap"),
    (ya(40e3), "Figurative sculpture in Europe", "sap"),
    (ya(40e3), "The earliest known sewing needle", "sap"),
    (ya(36e3), "Chauvet Cave is painted", "sap"),
    (ya(35e3), "Ground stone technology in Australia", "sap"),
    (ya(32e3), "Oats ground and heated at Grotta Paglicci", "sap"),
    (ya(28e3), "Woven textiles at Dolni Vestonice", "sap"),
    (ya(25e3), "Houses built of mammoth bone", "sap"),
    (ya(23e3), "Wild cereals gathered at Ohalo", "sap"),
    (ya(23e3), "Fish hooks for open water", "sap"),
    (ya(20e3), "The first clay pots, at Xianrendong", "sap"),
    (ya(17e3), "Lascaux is painted", "sap"),
    (ya(17e3), "Carved atlatls", "sap"),
    (ya(14.2e3), "The oldest undisputed dog burial", "sap"),
    (ya(13e3), "Clovis points in New Mexico", "sap"),
    (ya(10e3), "The earliest fish traps", "sap"),
    # ---------------------------------------------------- farming and cities
    (bce(9000), "Farming on the Fertile Crescent", "far"),
    (bce(8500), "Sheep and goats are domesticated", "far"),
    (bce(7000), "Millet and rice farmed in China", "far"),
    (bce(6700), "Maize domesticated in Mesoamerica", "far"),
    (bce(6500), "Farming in the Indus valley", "far"),
    (bce(5000), "Irrigation in Mesopotamia", "far"),
    (bce(5000), "Wheat and barley in the Fayum", "far"),
    (bce(4500), "Rice domesticated in India", "far"),
    (bce(4000), "Sorghum farmed in Sudan", "far"),
    (bce(4000), "Donkeys domesticated in Africa", "far"),
    (bce(4000), "Taro drained and grown at Kuk Swamp", "far"),
    (bce(3400), "Sumerian cuneiform", "far"),
    (bce(3400), "The potter's wheel", "far"),
    (bce(3000), "Yam and oil palm in West Africa", "far"),
    (bce(2600), "Planned streets at Mohenjo-daro", "far"),
    (bce(2560), "The Great Pyramid of Giza", "far"),
    (bce(2500), "Stonehenge", "far"),
    (bce(2100), "The Epic of Gilgamesh", "far"),
    (bce(2000), "Corn and beans in North America", "far"),
    (bce(1754), "The Code of Hammurabi", "far"),
    (bce(1500), "Terracing in the Andes", "far"),
    (bce(1200), "Oracle bones in Shang China", "far"),
    (bce(1050), "The Phoenician alphabet", "far"),
    (bce(1046), "The Zhou claim the mandate of heaven", "far"),
    (bce(1000), "The dromedary is domesticated in Arabia", "far"),
    (bce(500), "Iron farming tools in West Africa", "far"),
    (bce(200), "The Nazca lines", "far"),
    (bce(100), "The Maya long count", "far"),
    # ------------------------------------------------- states and empires
    (bce(1600), "The Hittite empire", "sta"),
    (bce(1200), "The Olmec at San Lorenzo", "sta"),
    (bce(800), "The Etruscans in Italy", "sta"),
    (bce(753), "The founding of Rome", "sta"),
    (bce(550), "The Persian empire", "sta"),
    (bce(330), "Alexander of Macedon", "sta"),
    (bce(206), "The Han dynasty", "sta"),
    (ce(1000), "Song dynasty innovations", "sta"),
    (ce(1000), "Polynesians settle the last Pacific islands", "sta"),
    (ce(1066), "The Norman conquest of England", "sta"),
    (ce(1100), "Cahokia at its peak", "sta"),
    (ce(1150), "The Zagwe dynasty in Ethiopia", "sta"),
    (ce(1206), "The Mongol empire", "sta"),
    (ce(1215), "Magna Carta", "sta"),
    (ce(1235), "The Mali empire", "sta"),
    (ce(1275), "Marco Polo reaches China", "sta"),
    (ce(1299), "The Ottoman empire", "sta"),
    (ce(1300), "Great Zimbabwe at its peak", "sta"),
    (ce(1300), "Maori settlement of New Zealand", "sta"),
    (ce(1325), "Tenochtitlan is founded", "sta"),
    (ce(1347), "The Black Death", "sta"),
    (ce(1368), "The Ming dynasty", "sta"),
    (ce(1400), "The Oyo empire", "sta"),
    (ce(1400), "The kingdom of Kongo", "sta"),
    (ce(1431), "Angkor is abandoned", "sta"),
    (ce(1438), "The Inca empire expands", "sta"),
    (ce(1441), "The Portuguese reach West Africa", "sta"),
    (ce(1453), "Constantinople falls", "sta"),
    (ce(1478), "The Spanish Inquisition", "sta"),
    (ce(1492), "The Columbian exchange begins", "sta"),
    (ce(1498), "Vasco da Gama reaches India", "sta"),
    (ce(1500), "The Songhai empire at its peak", "sta"),
    (ce(1521), "Cortes takes Tenochtitlan", "sta"),
    (ce(1526), "The Mughal empire", "sta"),
    (ce(1533), "Pizarro takes Cusco", "sta"),
    (ce(1600), "Sekigahara", "sta"),
    (ce(1603), "The Tokugawa shogunate", "sta"),
    (ce(1606), "Europeans first sight Australia", "sta"),
    (ce(1607), "Jamestown", "sta"),
    (ce(1618), "The Thirty Years War", "sta"),
    (ce(1620), "Plymouth Colony", "sta"),
    (ce(1642), "The English Civil War", "sta"),
    (ce(1644), "The Qing dynasty", "sta"),
    (ce(1688), "The Glorious Revolution", "sta"),
    (ce(1750), "The industrial revolution", "sta"),
    (ce(1756), "The Seven Years War", "sta"),
    (ce(1757), "East India Company rule in Bengal", "sta"),
    (ce(1768), "Cook's Pacific voyages", "sta"),
    (ce(1775), "The American Revolution", "sta"),
    (ce(1780), "The Atlantic slave trade at its peak", "sta"),
    (ce(1788), "The United States constitution", "sta"),
    (ce(1788), "The British colonisation of Australia", "sta"),
    (ce(1789), "The French Revolution", "sta"),
    (ce(1791), "The Haitian Revolution", "sta"),
    (ce(1803), "The Louisiana Purchase", "sta"),
    (ce(1804), "Napoleon is crowned emperor", "sta"),
    (ce(1815), "Waterloo", "sta"),
    (ce(1818), "The Zulu kingdom", "sta"),
    (ce(1821), "Mexican independence", "sta"),
    (ce(1821), "The Greek war of independence", "sta"),
    (ce(1822), "Brazilian independence", "sta"),
    (ce(1824), "The Black War in Tasmania", "sta"),
    (ce(1839), "The Opium Wars", "sta"),
    (ce(1840), "The Treaty of Waitangi", "sta"),
    (ce(1848), "The revolutions of 1848", "sta"),
    (ce(1849), "The California gold rush", "sta"),
    (ce(1850), "The Taiping rebellion", "sta"),
    (ce(1851), "The Australian gold rushes", "sta"),
    (ce(1853), "The Crimean War", "sta"),
    (ce(1861), "The American Civil War", "sta"),
    (ce(1868), "The Meiji restoration", "sta"),
    (ce(1869), "The Suez Canal", "sta"),
    (ce(1869), "The transcontinental railroad", "sta"),
    (ce(1871), "German unification", "sta"),
    (ce(1884), "The Berlin Conference and the scramble for Africa", "sta"),
    (ce(1898), "The Spanish-American War", "sta"),
    (ce(1900), "The Boxer rebellion", "sta"),
    (ce(1901), "The federation of Australia", "sta"),
    (ce(1904), "The Russo-Japanese War", "sta"),
    (ce(1912), "The Qing dynasty falls", "sta"),
    (ce(1914), "The First World War", "sta"),
    (ce(1939), "The Second World War", "sta"),
    (ce(1945), "The United Nations", "sta"),
    (ce(1960), "Seventeen African states become independent", "sta"),
    (ce(1991), "The Soviet Union dissolves", "sta"),
    # --------------------------------------------------- science and maths
    (bce(500), "Astronomy in India", "sci"),
    (bce(300), "A symbol for zero in Babylonian arithmetic", "sci"),
    (bce(300), "Euclid's Elements", "sci"),
    (ce(820), "Al-Khwarizmi's algebra", "sci"),
    (ce(1088), "The university of Bologna", "sci"),
    (ce(1100), "The compass is used at sea in China", "sci"),
    (ce(1202), "Fibonacci carries Hindu-Arabic numerals into Europe", "sci"),
    (ce(1250), "Gunpowder reaches Europe", "sci"),
    (ce(1300), "The mechanical clock", "sci"),
    (ce(1350), "Oresme's coordinate geometry", "sci"),
    (ce(1440), "Gutenberg's press", "sci"),
    (ce(1543), "Copernicus puts the Sun at the center", "sci"),
    (ce(1543), "Vesalius on the fabric of the human body", "sci"),
    (ce(1545), "Cardano's Ars Magna and the cubic", "sci"),
    (ce(1591), "Viete's symbolic algebra", "sci"),
    (ce(1608), "The telescope", "sci"),
    (ce(1609), "Kepler's laws", "sci"),
    (ce(1610), "Galileo sees the moons of Jupiter", "sci"),
    (ce(1614), "Napier's logarithms", "sci"),
    (ce(1628), "Harvey on the circulation of the blood", "sci"),
    (ce(1637), "Descartes' coordinate geometry", "sci"),
    (ce(1637), "Fermat states his last theorem", "sci"),
    (ce(1643), "Torricelli's barometer", "sci"),
    (ce(1654), "Pascal and Fermat lay out probability", "sci"),
    (ce(1670), "Newton and Leibniz build the calculus", "sci"),
    (ce(1676), "Van Leeuwenhoek sees bacteria", "sci"),
    (ce(1687), "Newton's Principia", "sci"),
    (ce(1712), "Newcomen's steam engine", "sci"),
    (ce(1713), "Bernoulli's law of large numbers", "sci"),
    (ce(1735), "Linnaeus orders the living world", "sci"),
    (ce(1752), "Franklin's kite", "sci"),
    (ce(1754), "Black isolates carbon dioxide", "sci"),
    (ce(1763), "Bayes' theorem", "sci"),
    (ce(1769), "Watt's separate condenser", "sci"),
    (ce(1775), "Lavoisier's chemical revolution", "sci"),
    (ce(1781), "Herschel finds Uranus", "sci"),
    (ce(1785), "Coulomb's law", "sci"),
    (ce(1788), "Lagrange's analytical mechanics", "sci"),
    (ce(1796), "Jenner's smallpox vaccination", "sci"),
    (ce(1800), "Volta's battery", "sci"),
    (ce(1801), "Gauss's Disquisitiones Arithmeticae", "sci"),
    (ce(1803), "Dalton's atomic theory", "sci"),
    (ce(1807), "Fourier analysis", "sci"),
    (ce(1808), "Gay-Lussac's gas laws", "sci"),
    (ce(1811), "Avogadro's hypothesis", "sci"),
    (ce(1821), "Cauchy makes analysis rigorous", "sci"),
    (ce(1829), "Lobachevsky's non-Euclidean geometry", "sci"),
    (ce(1831), "Faraday's induction", "sci"),
    (ce(1832), "Galois theory", "sci"),
    (ce(1843), "Hamilton's quaternions", "sci"),
    (ce(1854), "Boole's laws of thought", "sci"),
    (ce(1854), "Riemann's geometry", "sci"),
    (ce(1859), "Darwin's Origin of Species", "sci"),
    (ce(1862), "Pasteur and the germ theory", "sci"),
    (ce(1865), "Mendel's laws of inheritance", "sci"),
    (ce(1865), "Maxwell's equations", "sci"),
    (ce(1869), "Mendeleev's periodic table", "sci"),
    (ce(1872), "Klein's Erlangen program", "sci"),
    (ce(1874), "Cantor's set theory", "sci"),
    (ce(1876), "Bell patents the telephone", "sci"),
    (ce(1879), "Edison's light bulb", "sci"),
    (ce(1882), "Koch finds the tuberculosis bacillus", "sci"),
    (ce(1885), "The first automobile", "sci"),
    (ce(1887), "Hertz makes radio waves", "sci"),
    (ce(1895), "Rontgen's X-rays", "sci"),
    (ce(1896), "Becquerel finds radioactivity", "sci"),
    (ce(1898), "Curie isolates radium", "sci"),
    (ce(1900), "Planck's quantum", "sci"),
    (ce(1903), "The Wright brothers fly", "sci"),
    (ce(1905), "Einstein's special relativity", "sci"),
    (ce(1911), "Rutherford's nuclear atom", "sci"),
    (ce(1912), "Wegener proposes continental drift", "sci"),
    (ce(1928), "Fleming finds penicillin", "sci"),
    (ce(1929), "Hubble measures the expansion", "sci"),
    (ce(1953), "The structure of DNA", "sci"),
    (ce(1961), "The first human in orbit", "sci"),
    (ce(1969), "The first landing on the Moon", "sci"),
    (ce(2003), "The human genome is sequenced", "sci"),
    (ce(2012), "The Higgs boson", "sci"),
    (ce(2015), "Gravitational waves are detected", "sci"),
    (ce(2021), "The James Webb Space Telescope launches", "sci"),
    # ------------------------------------------------------- arts and belief
    (bce(500), "Confucius teaches", "art"),
    (bce(500), "Buddhism", "art"),
    (ce(33), "Christianity begins in Jerusalem", "art"),
    (ce(325), "The Council of Nicaea", "art"),
    (ce(622), "The hijra, and the start of the Islamic calendar", "art"),
    (ce(1000), "Beowulf is written down", "art"),
    (ce(1000), "Romanesque architecture", "art"),
    (ce(1054), "The schism between Rome and Constantinople", "art"),
    (ce(1095), "The First Crusade", "art"),
    (ce(1100), "The Song of Roland", "art"),
    (ce(1140), "Gothic architecture", "art"),
    (ce(1180), "The Arthurian romances", "art"),
    (ce(1204), "The Fourth Crusade sacks Constantinople", "art"),
    (ce(1209), "The Franciscan order", "art"),
    (ce(1216), "The Dominican order", "art"),
    (ce(1270), "Aquinas writes the Summa Theologica", "art"),
    (ce(1300), "Giotto remakes painting", "art"),
    (ce(1309), "The Avignon papacy", "art"),
    (ce(1320), "Dante's Divine Comedy", "art"),
    (ce(1378), "The Western Schism", "art"),
    (ce(1390), "Chaucer's Canterbury Tales", "art"),
    (ce(1400), "The Renaissance begins in Italy", "art"),
    (ce(1431), "Joan of Arc is burned", "art"),
    (ce(1440), "Donatello's David", "art"),
    (ce(1455), "The Gutenberg Bible", "art"),
    (ce(1485), "Botticelli's Birth of Venus", "art"),
    (ce(1495), "Leonardo's Last Supper", "art"),
    (ce(1504), "Michelangelo's David", "art"),
    (ce(1511), "Raphael's School of Athens", "art"),
    (ce(1511), "Erasmus, In Praise of Folly", "art"),
    (ce(1512), "The Sistine Chapel ceiling", "art"),
    (ce(1517), "Luther's ninety-five theses", "art"),
    (ce(1521), "The Diet of Worms", "art"),
    (ce(1532), "Machiavelli's The Prince", "art"),
    (ce(1535), "Rabelais, Gargantua and Pantagruel", "art"),
    (ce(1536), "Calvin's Institutes", "art"),
    (ce(1545), "The Council of Trent", "art"),
    (ce(1580), "Montaigne's Essays", "art"),
    (ce(1600), "Shakespeare at the Globe", "art"),
    (ce(1600), "Caravaggio's chiaroscuro", "art"),
    (ce(1605), "Cervantes, Don Quixote", "art"),
    (ce(1604), "The Guru Granth Sahib is compiled", "art"),
    (ce(1611), "The King James Bible", "art"),
    (ce(1620), "Bacon's Novum Organum", "art"),
    (ce(1637), "Descartes' Discourse on Method", "art"),
    (ce(1642), "Rembrandt's Night Watch", "art"),
    (ce(1651), "Hobbes' Leviathan", "art"),
    (ce(1667), "Milton's Paradise Lost", "art"),
    (ce(1677), "Spinoza's Ethics", "art"),
    (ce(1682), "Versailles", "art"),
    (ce(1690), "Locke's Essay Concerning Human Understanding", "art"),
    (ce(1721), "Bach's Brandenburg Concertos", "art"),
    (ce(1726), "Swift's Gulliver's Travels", "art"),
    (ce(1739), "Hume's Treatise of Human Nature", "art"),
    (ce(1742), "Handel's Messiah", "art"),
    (ce(1751), "Diderot's Encyclopedie", "art"),
    (ce(1755), "Johnson's Dictionary", "art"),
    (ce(1759), "Voltaire's Candide", "art"),
    (ce(1762), "Rousseau's Social Contract", "art"),
    (ce(1776), "Smith's Wealth of Nations", "art"),
    (ce(1781), "Kant's Critique of Pure Reason", "art"),
    (ce(1787), "Mozart's Don Giovanni", "art"),
    (ce(1789), "Blake's Songs of Innocence", "art"),
    (ce(1792), "Wollstonecraft's Vindication", "art"),
    (ce(1798), "Wordsworth and Coleridge's Lyrical Ballads", "art"),
    (ce(1808), "Goethe's Faust", "art"),
    (ce(1813), "Austen's Pride and Prejudice", "art"),
    (ce(1819), "Byron begins Don Juan", "art"),
    (ce(1821), "Hegel's Philosophy of Right", "art"),
    (ce(1824), "Beethoven's ninth symphony", "art"),
    (ce(1831), "Hugo's Notre-Dame de Paris", "art"),
    (ce(1835), "Balzac begins the Human Comedy", "art"),
    (ce(1838), "Dickens' Oliver Twist", "art"),
    (ce(1848), "Marx and Engels' Communist Manifesto", "art"),
    (ce(1854), "Thoreau's Walden", "art"),
    (ce(1857), "Flaubert's Madame Bovary", "art"),
    (ce(1857), "Baudelaire's Les Fleurs du mal", "art"),
    (ce(1860), "Impressionism", "art"),
    (ce(1865), "Carroll's Alice in Wonderland", "art"),
    (ce(1866), "Dostoevsky's Crime and Punishment", "art"),
    (ce(1869), "Tolstoy's War and Peace", "art"),
    (ce(1876), "Wagner completes the Ring", "art"),
    (ce(1879), "Ibsen's A Doll's House", "art"),
    (ce(1883), "Nietzsche's Thus Spoke Zarathustra", "art"),
    (ce(1885), "Post-Impressionism", "art"),
    (ce(1890), "Wilde's The Picture of Dorian Gray", "art"),
    (ce(1891), "Hardy's Tess of the d'Urbervilles", "art"),
    (ce(1900), "Freud's Interpretation of Dreams", "art"),
    (ce(1904), "Chekhov's The Cherry Orchard", "art"),
    # ------------------------------------------------------ world population
    (bce(10000), "About 4 million people", "pop"),
    (bce(5000), "About 5 million", "pop"),
    (bce(4000), "About 7 million", "pop"),
    (bce(3000), "About 14 million", "pop"),
    (bce(2000), "About 27 million", "pop"),
    (bce(1000), "About 50 million", "pop"),
    (bce(500), "About 100 million", "pop"),
    (ce(1), "About 190 million", "pop"),
    (ce(1000), "About 295 million", "pop"),
    (ce(1500), "About 460 million", "pop"),
    (ce(1700), "About 600 million", "pop"),
    (ce(1800), "About 990 million", "pop"),
    (ce(1900), "1.65 billion", "pop"),
    (ce(1927), "2 billion", "pop"),
    (ce(1974), "4 billion", "pop"),
    (ce(2000), "6.1 billion", "pop"),
    (ce(2024), "8.2 billion", "pop"),
]

# What the notebook said, and why it now says something else. Kept so the
# change from the source dataset is on the record.
FIXED = [
    ("The cosmic dark ages", "began 13.796 Ga, before the Big Bang itself",
     "the dark ages run from recombination to reionization, and end 13.4 Ga"),
    ("The giant planets", "4.59 Ga, before the Sun",
     "Jupiter's core grew within a few million years of the first solids, "
     "4.564 Ga"),
    ("The Moon", "4.53 Ga", "the giant impact is now dated near 4.51 Ga"),
    ("The earliest known galaxies", "13.407 Ga",
     "MoM z14, announced in 2025, sits at 13.52 Ga"),
    ("The Permian extinction", "an interval of 250 to 200 Ma",
     "it is a short event at 251.9 Ma"),
    ("The Chicxulub impact", "65 Ma", "66.0 Ma"),
    ("The first human", "Homo sapiens at 2.8 Ma",
     "2.8 Ma is the earliest jaw assigned to the genus Homo"),
    ("Acheulean handaxes", "2.8 Ma", "1.76 Ma at Kokiselei"),
    ("Homo sapiens", "200 ka", "315 ka at Jebel Irhoud"),
    ("Twisted plant fibre", "90 ka",
     "the Neanderthal cord from Abri du Maras is 50 ka"),
    ("Australia", "settled 55 ka", "65 ka at Madjedbebe"),
    ("The domestic dog", "30 ka",
     "the oldest undisputed dog burial is 14.2 ka, and the date is contested"),
    ("Pigs in New Guinea", "7000 BCE", "they arrive within the last few "
     "thousand years, so the mark was dropped"),
    ("The dromedary", "3000 BCE", "about 1000 BCE"),
    ("Adwa", "an Ethiopian victory in 1340",
     "Adwa was fought in 1896, and the mark was dropped"),
    ("The Inca empire", "1200", "the kingdom of Cusco is that old, the empire "
     "expands from 1438"),
    ("Angkor", "abandoned about 1400", "1431"),
    ("A world population of one billion", "1750", "about 1800"),
    ("A world population of two billion", "1900", "1927"),
]
