#!/usr/bin/env python3
"""The data behind galaxies.html, each figure with its source.

Diameters are D25 where published (RC3 and the NASA/IPAC Extragalactic
Database, as carried on the Wikipedia article for each galaxy); the Milky
Way's is the stellar disc of Goodwin, Gribbin and Hendry (1998). Milky Way
structure: Bland-Hawthorn and Gerhard (2016). The Sun's distance to the
centre: GRAVITY Collaboration (2019). Arms: Reid and others (2019). Local
Group members: McConnachie (2012).
"""

import apa

SUN_R = 8.2          # kpc, GRAVITY 2019 gives 8.178 +- 0.026

# ---- Hubble's classes ----
# k, group, name, defined by, examples, where the Milky Way stands, card text
KINDS = [
    dict(k="E0", g="Elliptical", n="E0, a round elliptical",
         **{"def": "an ellipsoid of old stars with no disc; the number is ten times one minus the axis ratio, so E0 looks round"},
         ex="M87 in Virgo; M49",
         mw="the Milky Way's bulge alone would look something like this",
         b="Ellipticals hold mostly old, red stars moving on random orbits, with little gas left to make new ones. The biggest galaxies known are ellipticals, grown by swallowing others.",
         s="Hubble 1926; Buta 2013"),
    dict(k="E3", g="Elliptical", n="E3, a moderately flattened elliptical",
         **{"def": "axis ratio 0.7; how flat it looks depends on the angle it is seen from"},
         ex="M59; NGC 4621", mw="no counterpart",
         b="Hubble's number for an elliptical is only the shape on the sky. A cigar seen end-on is an E0, so the class says less about the galaxy than the spiral classes do.",
         s="Hubble 1926"),
    dict(k="E7", g="Elliptical", n="E7, the flattest elliptical",
         **{"def": "axis ratio 0.3, the flattest an elliptical is seen"},
         ex="NGC 3115 is often given as E7 or S0", mw="no counterpart",
         b="Nothing rounder than about E7 exists, which is a clue: past that flattening a galaxy has a disc, and belongs to the next class along.",
         s="Hubble 1936"),
    dict(k="S0", g="Lenticular", n="S0, a lenticular",
         **{"def": "a disc and a large bulge, with no spiral arms and little gas"},
         ex="NGC 5866; NGC 3115; the Sombrero is on the border with Sa",
         mw="a Milky Way that had used up or lost its gas",
         b="Hubble put S0 at the join of the fork as the missing link between ellipticals and spirals. Many are spirals that lost their gas in a cluster and stopped making arms.",
         s="Hubble 1936; Buta 2013"),
    dict(k="Sa", g="Spiral", n="Sa, tightly wound",
         **{"def": "a large bulge and arms wound tight, at a pitch of about ten degrees"},
         ex="the Sombrero, M104; NGC 4594", mw="our bulge is smaller and our arms more open than this",
         b="The letter runs a to c as the bulge shrinks, the arms open out, and the gas fraction rises. An Sa is mostly bulge with a thin, tightly coiled disc.",
         s="Hubble 1926"),
    dict(k="Sb", g="Spiral", n="Sb, the middle of the sequence",
         **{"def": "a moderate bulge and arms at a pitch near fifteen degrees"},
         ex="Andromeda, M31; Bode's galaxy, M81", mw="Andromeda, our nearest large neighbour, is an Sb",
         b="Andromeda is the archetype: a bright bulge, well defined arms, dust lanes, and a disc that keeps making stars, slowly.",
         s="Hubble 1926"),
    dict(k="Sc", g="Spiral", n="Sc, loosely wound",
         **{"def": "a small bulge and open, knotty arms at a pitch of twenty degrees or more"},
         ex="the Triangulum galaxy, M33; NGC 628", mw="Triangulum, the Local Group's third spiral, is an Sc",
         b="An Sc is mostly disc, rich in gas, with arms lit by young blue stars and the pink of hydrogen around them. They are the spirals that look most like the pictures.",
         s="Hubble 1926"),
    dict(k="SBa", g="Barred spiral", n="SBa, barred and tight",
         **{"def": "a straight bar of stars through the centre, with tightly wound arms leaving its ends"},
         ex="NGC 4314; NGC 2787 sits on the border with SB0", mw="our bar is longer than our bulge is wide, as here",
         b="The bar is a stellar wave, not a fixed set of stars. It funnels gas inward, feeds the centre, and most spirals have one when looked at in the infrared.",
         s="Hubble 1936; Eskridge and others 2000"),
    dict(k="SBb", g="Barred spiral", n="SBb, barred, middle of the sequence",
         **{"def": "a bar with arms at a moderate pitch"},
         ex="the Great Barred Spiral, NGC 1365", mw="the class just inside the Milky Way's",
         b="NGC 1365 shows the shape from outside: a bar as long as the bulge is wide three times over, and two grand arms unwinding from its tips.",
         s="Hubble 1936"),
    dict(k="SBc", g="Barred spiral", n="SBc, barred and open",
         **{"def": "a bar with a small bulge and open arms"},
         ex="NGC 7479; NGC 1073", mw="the class just outside the Milky Way's",
         b="The most open barred spirals shade into the irregulars: the Large Magellanic Cloud has a bar and one arm, and is called SBm, a barred Magellanic spiral.",
         s="Hubble 1936; Buta 2013"),
    dict(k="Irr", g="Irregular", n="Irr, no symmetry to speak of",
         **{"def": "neither an ellipsoid nor a disc with arms; gas-rich and forming stars in clumps"},
         ex="the Small Magellanic Cloud; IC 10; NGC 1427A", mw="our two brightest satellites are irregulars",
         b="Most irregulars are small, and most small galaxies are irregular or spheroidal, so the fork describes the bright galaxies well and the common ones poorly.",
         s="Hubble 1926; McConnachie 2012"),
]

# ---- galaxies to scale ----
# k, name, class for the drawing, diameter kpc, diameter text, distance,
# card text, source
SIZES = [
    dict(k="ic1101", n="IC 1101", c="E4", d=123.7, dTxt="about 124 kpc, 400,000 light years",
         dist="320 Mpc, a billion light years", t="Giant elliptical, cD",
         b="The central galaxy of the cluster Abell 2029, and among the largest known. Its faint outer halo runs on far past this edge, which is where old claims of six million light years came from.",
         s="Wikipedia, IC 1101"),
    dict(k="m101", n="Pinwheel, M101", c="Sc", d=51.8, dTxt="52 kpc, 170,000 light years",
         dist="6.4 Mpc, 21 million light years", t="Spiral, SAB(rs)cd",
         b="A face-on spiral nearly twice the Milky Way across, with a trillion stars and a disc lopsided by a companion's pull.",
         s="Wikipedia, Pinwheel Galaxy"),
    dict(k="m31", n="Andromeda, M31", c="Sb", d=46.6, dTxt="46.6 kpc, 152,000 light years",
         dist="765 kpc, 2.5 million light years", t="Spiral, SA(s)b",
         b="The nearest large galaxy and the largest in the Local Group, about a trillion stars to our few hundred billion. It and the Milky Way are falling toward each other and will merge in about four and a half billion years.",
         s="Wikipedia, Andromeda Galaxy; McConnachie 2012"),
    dict(k="m87", n="M87", c="E1", d=40.6, dTxt="41 kpc, 132,000 light years",
         dist="16.4 Mpc, 53 million light years", t="Giant elliptical, E0-1 pec",
         b="The giant at the heart of the Virgo cluster, with a black hole of six and a half billion suns whose shadow was the first ever imaged, in 2019.",
         s="Wikipedia, Messier 87"),
    dict(k="ngc1300", n="NGC 1300", c="SBb", d=33.6, dTxt="34 kpc, 110,000 light years",
         dist="18.7 Mpc, 61 million light years", t="Barred spiral, SB(rs)bc",
         b="The textbook barred spiral, and about the Milky Way's size and class. Seen face-on, it is the nearest thing to a photograph of our own galaxy from outside.",
         s="Wikipedia, NGC 1300"),
    dict(k="mw", n="the Milky Way", c="MW", d=26.8, dTxt="26.8 kpc, 87,400 light years, the stellar disc",
         dist="the Sun is 8.2 kpc from its centre", t="Barred spiral, SBbc",
         b="Our own, drawn face-on with the Sun where it is: a little more than halfway out, in a minor spur between two arms. The commonly quoted 100,000 light years counts fainter outskirts than the disc edge drawn here.",
         s="Goodwin, Gribbin and Hendry 1998; GRAVITY 2019"),
    dict(k="m51", n="Whirlpool, M51", c="Sc", d=23.6, dTxt="24 kpc, 77,000 light years",
         dist="8.6 Mpc, 28 million light years", t="Spiral, SA(s)bc pec",
         b="A spiral with a small companion tugging at the end of one arm, which is what drew the arms out so cleanly.",
         s="Wikipedia, Whirlpool Galaxy"),
    dict(k="m33", n="Triangulum, M33", c="Sc", d=18.7, dTxt="18.7 kpc, 61,000 light years",
         dist="840 kpc, 2.7 million light years", t="Spiral, SA(s)cd",
         b="The third spiral of the Local Group and probably a satellite of Andromeda, with some forty billion stars.",
         s="Wikipedia, Triangulum Galaxy; McConnachie 2012"),
    dict(k="cena", n="Centaurus A", c="E2", d=18.4, dTxt="18 kpc, 60,000 light years",
         dist="3.8 Mpc, 12 million light years", t="Elliptical with a dust lane, S0 pec",
         b="An elliptical that swallowed a spiral and wears its dust as a band across the middle; the nearest radio galaxy, with jets a million light years long.",
         s="Wikipedia, Centaurus A"),
    dict(k="m104", n="Sombrero, M104", c="Sa", d=15.0, dTxt="15 kpc, 49,000 light years",
         dist="9.55 Mpc, 31 million light years", t="Spiral, SA(s)a",
         b="A large bulge, a thin dust ring, and a disc seen six degrees from edge-on: the Sa end of the fork made visible.",
         s="Wikipedia, Sombrero Galaxy"),
    dict(k="lmc", n="Large Magellanic Cloud", c="Irr", d=9.9, dTxt="9.9 kpc, 32,000 light years",
         dist="50 kpc, 163,000 light years", t="Magellanic spiral, SB(s)m",
         b="Our largest satellite, with a bar and one ragged arm. It is falling in for the first time, and its gas trails behind it across a third of the sky.",
         s="Wikipedia, Large Magellanic Cloud; McConnachie 2012"),
    dict(k="smc", n="Small Magellanic Cloud", c="Irr", d=5.8, dTxt="5.8 kpc, 19,000 light years",
         dist="62 kpc, 200,000 light years", t="Irregular, SB(s)m pec",
         b="The Large Cloud's companion, torn by it, with a bridge of gas and stars between the two.",
         s="Wikipedia, Small Magellanic Cloud; McConnachie 2012"),
    dict(k="sgr", n="Sagittarius dwarf", c="E3", d=3.0, dTxt="about 3 kpc, 10,000 light years, the core",
         dist="26 kpc, 85,000 light years", t="Dwarf spheroidal",
         b="A satellite being pulled apart as it loops through our disc, its stars strewn in a stream around the whole sky. It has crossed the disc several times, and each pass stirs us.",
         s="McConnachie 2012"),
]

# ---- parts of the Milky Way ----
PARTS = [
    dict(k="whole", n="The Milky Way", nums=[
            ["stars", "100 to 400 billion"], ["stellar mass", "about 5 times 10^10 suns"],
            ["total mass", "about 1.3 times 10^12 suns, most of it dark"],
            ["disc", "about 30 kpc across, 0.3 kpc thick"], ["Sun's orbit", "8.2 kpc out, 238 km/s, about 230 million years round"]],
         b="A barred spiral of the class SBbc, one of two large spirals in the Local Group. Everything visible to the naked eye at night is inside it, and the band across the sky is its disc seen from within.",
         mw="A barred spiral, SBbc. The bar is seen nearly end-on from the Sun, which is why it took until the 1990s to be sure of it; from outside the galaxy would look much like NGC 1300.",
         s="Bland-Hawthorn and Gerhard 2016; McConnachie 2012"),
    dict(k="bar", n="The bar", nums=[["half-length", "about 5 kpc"], ["angle", "28 degrees from the Sun's line to the centre"],
            ["mass", "about 1.9 times 10^10 suns with the bulge"]],
         b="A bar of stars through the centre, seen from the Sun nearly end-on, which hid it until infrared surveys traced its asymmetric glow. It turns as a pattern about once every 200 million years and steers gas inward.",
         s="Bland-Hawthorn and Gerhard 2016"),
    dict(k="bulge", n="The bulge", nums=[["radius", "about 1.5 kpc"], ["shape", "a boxy peanut, seen edge-on"], ["stars", "mostly old, over 10 billion years"]],
         b="The bulge is the bar's thick middle, puffed up by the bar itself, and from the side it has the peanut shape of a bar seen at an angle. Its stars are old and rich in heavy elements.",
         s="Bland-Hawthorn and Gerhard 2016"),
    dict(k="sgra", n="Sagittarius A*", nums=[["mass", "4.3 million suns"], ["distance", "8.178 kpc, measured to 0.3 percent"], ["size", "an event horizon about 0.08 au across"]],
         b="The black hole at the centre. Stars orbit it fast enough to weigh it, and the orbit of one, S2, gave the distance to the centre of the galaxy that this whole drawing is scaled by.",
         s="GRAVITY Collaboration 2019, 2022"),
    dict(k="sun", n="The Sun", nums=[["from the centre", "8.2 kpc, 26,700 light years"], ["above the plane", "about 25 pc"], ["speed", "238 km/s, about one turn per 230 million years"]],
         b="A little more than halfway out to the disc's edge, in a minor spur between the Sagittarius and Perseus arms. The Sun has gone round about twenty times since it formed.",
         s="GRAVITY 2019; Bland-Hawthorn and Gerhard 2016"),
    dict(k="thin", n="The thin disc", nums=[["scale height", "about 300 pc"], ["scale length", "about 2.6 kpc"], ["mass", "about 3.5 times 10^10 suns in stars"]],
         h=0.3,
         b="Where the gas, the young stars and the spiral arms are, and where the Sun is. Its thickness is a hundredth of its width, which is why the Milky Way is a band and not a blob.",
         s="Bland-Hawthorn and Gerhard 2016"),
    dict(k="thick", n="The thick disc", nums=[["scale height", "about 900 pc"], ["stars", "old, over 10 billion years, poorer in heavy elements"], ["mass", "about 6 times 10^9 suns"]],
         h=0.9,
         b="A puffier, older disc around the thin one, likely the thin disc of an earlier age heated by a merger, or born thick in a turbulent young galaxy.",
         s="Bland-Hawthorn and Gerhard 2016"),
    dict(k="halo", n="The stellar halo", nums=[["reach", "more than 100 kpc, faintly"], ["mass", "about 10^9 suns in stars, a hundredth of the disc"], ["dark matter", "about 10^12 suns out to some 200 kpc"]],
         b="A sparse round cloud of the oldest stars, much of it the wreckage of swallowed dwarfs, wrapped in a dark matter halo that outweighs everything drawn here ten to one and reaches fourteen times farther.",
         s="Bland-Hawthorn and Gerhard 2016"),
    dict(k="gcs", n="Globular clusters", nums=[["count", "about 150 known"], ["ages", "11 to 13 billion years"], ["stars each", "a hundred thousand to a million"]],
         b="Dense balls of old stars orbiting through the halo, some of them among the oldest objects known. Their distribution was how Shapley found, in 1918, that the Sun is not at the centre.",
         s="Bland-Hawthorn and Gerhard 2016"),
    dict(k="perseus", n="The Perseus arm", arm=True, major=True, pitch=9.4, rSun=10.2, labelT=-1.9, c="#b48cf2",
         nums=[["from the Sun", "about 2 kpc outward"], ["pitch", "9.4 degrees"]],
         b="The major arm just outside the Sun's orbit, traced by masers in star-forming regions whose parallaxes gave its pitch. The Double Cluster in Perseus lies along it.",
         s="Reid and others 2019"),
    dict(k="sagcar", n="The Sagittarius-Carina arm", arm=True, major=False, pitch=17.1, rSun=6.7, labelT=-0.25, c="#9be564",
         nums=[["from the Sun", "about 1.5 kpc inward"], ["pitch", "17.1 degrees"]],
         b="The arm just inside the Sun's orbit, rich in nebulae toward Sagittarius: the Lagoon, the Trifid, the Eagle and the Omega nebula all lie along it.",
         s="Reid and others 2019"),
    dict(k="sctcen", n="The Scutum-Centaurus arm", arm=True, major=True, pitch=13.1, rSun=4.9, labelT=1.7, c="#e0a458",
         nums=[["from the Sun", "about 3.3 kpc inward"], ["pitch", "13.1 degrees"]],
         b="One of the two major arms, starting at the near end of the bar and sweeping round the far side of the galaxy.",
         s="Reid and others 2019"),
    dict(k="outer", n="The Norma-Outer arm", arm=True, major=False, pitch=10.5, rSun=13.4, labelT=0.9, c="#6ee7f2",
         nums=[["from the Sun", "about 5 kpc outward"], ["pitch", "10.5 degrees"]],
         b="The outermost arm traced so far, sparse and far, where the disc is thinning toward its edge.",
         s="Reid and others 2019"),
    dict(k="spur", n="The Local arm, or Orion spur", c="#ffb02e",
         nums=[["length", "about 5 kpc traced"], ["pitch", "11.4 degrees"], ["holds", "the Sun, and the Orion nebula"]],
         b="Long called a spur between two arms, it turned out from the parallaxes to be a real arm segment several kiloparsecs long, with the Sun riding in it.",
         s="Reid and others 2019"),
]

# ---- the Local Group, McConnachie 2012 ----
# k, name, type (for the colour), tTxt, galactic l and b in degrees, distance kpc, size kpc, group
def _g(k, n, type_, tTxt, l, b, d, size, sizeTxt, group, body, big=False):
    return dict(k=k, n=n, type=type_, tTxt=tTxt, l=l, lat=b, d=d, size=size,
                sizeTxt=sizeTxt, group=group, b=body, big=big)

NEIGHBOURS = [
    _g("lmc", "Large Magellanic Cloud", "irregular", "Magellanic spiral, SB(s)m", 280.5, -32.9, 50, 9.9,
       "9.9 kpc across", "the Milky Way's satellites",
       "Our brightest satellite, visible to the eye from the south as a detached piece of the Milky Way.", True),
    _g("smc", "Small Magellanic Cloud", "irregular", "Irregular", 302.8, -44.3, 62, 5.8,
       "5.8 kpc across", "the Milky Way's satellites",
       "Bound to the Large Cloud and pulled about by it.", True),
    _g("sgr", "Sagittarius dwarf", "spheroidal", "Dwarf spheroidal", 5.6, -14.2, 26, 3.0,
       "about 3 kpc, the core", "the Milky Way's satellites",
       "The closest, and being torn into a stream around the whole sky."),
    _g("dra", "Draco", "spheroidal", "Dwarf spheroidal", 86.4, 34.7, 76, 1.0,
       "about 1 kpc", "the Milky Way's satellites",
       "A faint satellite so dominated by dark matter that its stars are a trace."),
    _g("umi", "Ursa Minor", "spheroidal", "Dwarf spheroidal", 105.0, 44.8, 76, 1.0,
       "about 1 kpc", "the Milky Way's satellites",
       "One of the oldest stellar populations known, all its stars formed in a single early burst."),
    _g("scl", "Sculptor", "spheroidal", "Dwarf spheroidal", 287.5, -83.2, 86, 1.0,
       "about 1 kpc", "the Milky Way's satellites",
       "The first dwarf spheroidal found, by Shapley in 1938."),
    _g("sex", "Sextans", "spheroidal", "Dwarf spheroidal", 243.5, 42.3, 86, 1.5,
       "about 1.5 kpc", "the Milky Way's satellites",
       "So diffuse it was not found until 1990."),
    _g("car", "Carina", "spheroidal", "Dwarf spheroidal", 260.1, -22.2, 105, 0.7,
       "about 0.7 kpc", "the Milky Way's satellites",
       "Formed its stars in several separate episodes billions of years apart."),
    _g("for", "Fornax", "spheroidal", "Dwarf spheroidal", 237.1, -65.7, 147, 2.0,
       "about 2 kpc", "the Milky Way's satellites",
       "The brightest of the dwarf spheroidals, with globular clusters of its own."),
    _g("leo2", "Leo II", "spheroidal", "Dwarf spheroidal", 220.2, 67.2, 233, 0.5,
       "about 0.5 kpc", "the Milky Way's satellites",
       "A distant satellite, mostly old stars."),
    _g("leo1", "Leo I", "spheroidal", "Dwarf spheroidal", 226.0, 49.1, 254, 0.8,
       "about 0.8 kpc", "the Milky Way's satellites",
       "The most distant of the classical satellites, and possibly on its first pass."),
    _g("phe", "Phoenix", "irregular", "Dwarf irregular, transitional", 272.2, -68.9, 415, 0.6,
       "about 0.6 kpc", "between the two big galaxies",
       "A dwarf between the irregular and spheroidal kinds, with a little gas left."),
    _g("n6822", "NGC 6822", "irregular", "Dwarf irregular", 25.3, -18.4, 490, 2.4,
       "about 2.4 kpc", "between the two big galaxies",
       "Barnard's galaxy, an isolated dwarf still making stars, found in 1884."),
    _g("n185", "NGC 185", "elliptical", "Dwarf elliptical", 120.8, -14.5, 617, 2.5,
       "about 2.5 kpc", "Andromeda's satellites",
       "A dwarf elliptical of Andromeda with a little dust and recent star formation at its heart."),
    _g("n147", "NGC 147", "elliptical", "Dwarf elliptical", 119.8, -14.3, 676, 3.0,
       "about 3 kpc", "Andromeda's satellites",
       "NGC 185's companion, the two a bound pair orbiting Andromeda."),
    _g("ic1613", "IC 1613", "irregular", "Dwarf irregular", 129.7, -60.6, 730, 3.0,
       "about 3 kpc", "between the two big galaxies",
       "An isolated dwarf irregular, useful for calibrating distances by its variable stars."),
    _g("ic10", "IC 10", "irregular", "Dwarf irregular, starburst", 119.0, -3.3, 750, 2.0,
       "about 2 kpc", "Andromeda's satellites",
       "The only starburst galaxy in the Local Group, hidden behind the dust of our own disc."),
    _g("m31", "Andromeda, M31", "spiral", "Spiral, SA(s)b", 121.2, -21.6, 765, 46.6,
       "46.6 kpc across", "the Local Group's other large galaxy",
       "The other big galaxy. The Local Group is, roughly, these two and everything that orbits them.", True),
    _g("leoa", "Leo A", "irregular", "Dwarf irregular", 196.9, 52.4, 800, 1.0,
       "about 1 kpc", "between the two big galaxies",
       "A gas-rich dwarf that formed most of its stars late."),
    _g("m32", "M32", "elliptical", "Compact elliptical", 121.15, -21.98, 805, 2.5,
       "about 2.5 kpc", "Andromeda's satellites",
       "A dense compact elliptical right against Andromeda's disc, probably the stripped core of a larger galaxy."),
    _g("m110", "M110", "elliptical", "Dwarf elliptical", 120.7, -21.1, 824, 5.0,
       "about 5 kpc", "Andromeda's satellites",
       "Andromeda's largest dwarf elliptical companion, with dust and young stars unusual for the kind."),
    _g("m33", "Triangulum, M33", "spiral", "Spiral, SA(s)cd", 133.6, -31.3, 840, 18.7,
       "18.7 kpc across", "probably Andromeda's satellite",
       "The third spiral, a third the Milky Way's size, likely bound to Andromeda.", True),
    _g("tuc", "Tucana", "spheroidal", "Dwarf spheroidal", 322.9, -47.4, 880, 0.5,
       "about 0.5 kpc", "on the Local Group's edge",
       "An isolated dwarf spheroidal far from either big galaxy, which is rare for the kind."),
    _g("peg", "Pegasus dwarf", "irregular", "Dwarf irregular, transitional", 94.8, -43.5, 920, 1.5,
       "about 1.5 kpc", "on the Local Group's edge",
       "An outlying dwarf with a little gas."),
    _g("wlm", "WLM", "irregular", "Dwarf irregular", 75.9, -73.6, 930, 3.4,
       "about 3.4 kpc", "on the Local Group's edge",
       "Wolf-Lundmark-Melotte, an isolated dwarf on the far edge, evolving on its own."),
]

REFS = [
    (apa.article("Hubble, E. P.", 1926, "Extragalactic nebulae", "The Astrophysical Journal", 64, None,
                 "321-369", "https://doi.org/10.1086/143018"),
     "The classification the Kinds view draws."),
    (apa.book("Hubble, E.", 1936, "The realm of the nebulae", "Yale University Press"),
     "The tuning fork diagram itself."),
    (apa.article("Buta, R. J.", 2013, "Galaxy morphology", "Planets, Stars and Stellar Systems", 6, None,
                 "1-89", "https://doi.org/10.1007/978-94-007-5609-0_1"),
     "The modern reading of the classes."),
    (apa.article("Eskridge, P. B., Frogel, J. A., Pogge, R. W., Quillen, A. C., Davies, R. L., DePoy, D. L., "
                 "Houdashelt, M. L., Kuchinski, L. E., Ram&iacute;rez, S. V., Sellgren, K., Terndrup, D. M., &amp; "
                 "Tiede, G. P.", 2000, "The frequency of barred spiral galaxies in the near-infrared",
                 "The Astronomical Journal", 119, 2, "536-544", "https://doi.org/10.1086/301203"),
     "Most spirals show a bar in the infrared."),
    (apa.article("Bland-Hawthorn, J., &amp; Gerhard, O.", 2016,
                 "The galaxy in context: Structural, kinematic, and integrated properties",
                 "Annual Review of Astronomy and Astrophysics", 54, None, "529-596",
                 "https://doi.org/10.1146/annurev-astro-081915-023441"),
     "The Milky Way's parts, masses and dimensions."),
    (apa.article("GRAVITY Collaboration", 2019,
                 "A geometric distance measurement to the Galactic center black hole with 0.3% uncertainty",
                 "Astronomy &amp; Astrophysics", 625, None, "L10", "https://doi.org/10.1051/0004-6361/201935656"),
     "The Sun's distance to the centre, 8.178 kpc."),
    (apa.article("GRAVITY Collaboration", 2022,
                 "Mass distribution in the Galactic Center based on interferometric astrometry of multiple stellar orbits",
                 "Astronomy &amp; Astrophysics", 657, None, "L12", "https://doi.org/10.1051/0004-6361/202142465"),
     "The mass of Sagittarius A*."),
    (apa.article("Reid, M. J., Menten, K. M., Brunthaler, A., Zheng, X. W., Dame, T. M., Xu, Y., Li, J., Sakai, N., "
                 "Wu, Y., Immer, K., Zhang, B., Sanna, A., Moscadelli, L., Rygl, K. L. J., Bartkiewicz, A., Hu, B., "
                 "Quiroga-Nu&ntilde;ez, L. H., &amp; van Langevelde, H. J.", 2019,
                 "Trigonometric parallaxes of high-mass star forming regions: Our view of the Milky Way",
                 "The Astrophysical Journal", 885, 2, "131", "https://doi.org/10.3847/1538-4357/ab4a11"),
     "The arms, their pitch angles and where they cross the Sun's line."),
    (apa.article("Goodwin, S. P., Gribbin, J., &amp; Hendry, M. A.", 1998, "The relative size of the Milky Way",
                 "The Observatory", 118, None, "201-208",
                 "https://ui.adsabs.harvard.edu/abs/1998Obs...118..201G"),
     "The stellar disc at 26.8 kpc."),
    (apa.article("McConnachie, A. W.", 2012,
                 "The observed properties of dwarf galaxies in and around the Local Group",
                 "The Astronomical Journal", 144, 1, "4", "https://doi.org/10.1088/0004-6256/144/1/4"),
     "Every position and distance in the Neighbours view."),
    (apa.book("de Vaucouleurs, G., de Vaucouleurs, A., Corwin, H. G., Buta, R. J., Paturel, G., &amp; Fouqu&eacute;, P.",
              1991, "Third reference catalogue of bright galaxies", "Springer",
              "https://doi.org/10.1007/978-1-4757-4363-0"),
     "The D25 diameters and the revised classes."),
    (apa.wiki("https://en.wikipedia.org/wiki/IC_1101"), "Diameter and distance, as carried from the literature."),
    (apa.wiki("https://en.wikipedia.org/wiki/Pinwheel_Galaxy"), "Diameter and distance."),
    (apa.wiki("https://en.wikipedia.org/wiki/Andromeda_Galaxy"), "Diameter, star count and the coming merger."),
    (apa.wiki("https://en.wikipedia.org/wiki/Messier_87"), "Diameter, distance and the black hole."),
    (apa.wiki("https://en.wikipedia.org/wiki/NGC_1300"), "Diameter and distance."),
    (apa.wiki("https://en.wikipedia.org/wiki/Whirlpool_Galaxy"), "Diameter and distance."),
    (apa.wiki("https://en.wikipedia.org/wiki/Triangulum_Galaxy"), "Diameter and star count."),
    (apa.wiki("https://en.wikipedia.org/wiki/Centaurus_A"), "Diameter and distance."),
    (apa.wiki("https://en.wikipedia.org/wiki/Sombrero_Galaxy"), "Diameter and distance."),
    (apa.wiki("https://en.wikipedia.org/wiki/Large_Magellanic_Cloud"), "Diameter."),
    (apa.wiki("https://en.wikipedia.org/wiki/Small_Magellanic_Cloud"), "Diameter."),
]
